define(["../Objects/AtomicArray",
        "../Objects/AtomicKeyPairArray",
        "../Objects/AtomicLink",
        "../Objects/Base",
        "../Objects/Component",
        "../Objects/Container",
        "../Objects/Controller",
        "../Objects/Entity",
        "../Objects/EventEmitter",
        "../Objects/EventQueue",
        "../Objects/InputHandle",
        "../Objects/Loader",
        "../Objects/Scene",
        "../Objects/System"
],
function (
    AtomicArray,
    AtomicKeyPairArray,
    AtomicLink,
    Base,
    Component,
    Container,
    Controller,
    Entity,
    EventEmitter,
    EventQueue,
    InputHandle,
    Loader,
    Scene,
    System
) {

    return {
        AtomicArray,
        AtomicKeyPairArray,
        AtomicLink,
        Base,
        Component,
        Container,
        Controller,
        Entity,
        EventEmitter,
        EventQueue,
        InputHandle,
        Loader,
        Scene,
        System
    };
});