// <autogen>
import { ILine } from './interfaces/ILine';
import { INormalizedVector } from './interfaces/INormalizedVector';
import { IPoint } from './interfaces/IPoint';
import { IPose } from './interfaces/IPose';
import { IShape } from './interfaces/IShape';
import { IVector } from './interfaces/IVector';
import { Vector } from './statics/Vector';
import {
  booleanContains,
  booleanOverlap,
  booleanPointInPolygon,
  booleanPointOnLine,
  centerOfMass,
  lineIntersect,
  intersect,
  rotatePointAboutOrigin,
  transformShape,
  fromPointsToGeoJSON,
  fromShapeToGeoJSON,
  fromGeoJSONCoordinatesToShapes,
  IBoundary,
  fromShapeToBoundary,
  getEuclideanDistanceBetweenPoints,
  getAngleBetweenPoints,
  getDirectionVectorAB,
  turf,
  geojson,
  area,
  bbox,
  difference,
  kinks,
  simplify,
  unkinkPolygon,
} from './geometry';
export {
  ILine,
  INormalizedVector,
  IPoint,
  IPose,
  IShape,
  IVector,
  Vector,
  booleanContains,
  booleanOverlap,
  booleanPointInPolygon,
  booleanPointOnLine,
  centerOfMass,
  lineIntersect,
  intersect,
  rotatePointAboutOrigin,
  transformShape,
  fromPointsToGeoJSON,
  fromShapeToGeoJSON,
  fromGeoJSONCoordinatesToShapes,
  IBoundary,
  fromShapeToBoundary,
  getEuclideanDistanceBetweenPoints,
  getAngleBetweenPoints,
  getDirectionVectorAB,
  turf,
  geojson,
  area,
  bbox,
  difference,
  kinks,
  simplify,
  unkinkPolygon,
};
// </autogen>
